# Generated by Django 3.1.2 on 2020-11-19 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url2',
            field=models.CharField(default=django.utils.timezone.now, max_length=2083),
            preserve_default=False,
        ),
    ]
