# Generated by Django 3.1.2 on 2020-11-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_url2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url2',
        ),
    ]
